# Generated by Django for VinylArt Organization Management

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('logo', models.ImageField(upload_to='org/logo/', max_length=255, verbose_name='الشعار')),
                ('slogan_ar', models.CharField(max_length=500, verbose_name='الشعار بالعربية')),
                ('slogan_en', models.CharField(max_length=500, verbose_name='الشعار بالإنجليزية')),
                ('about_ar', models.TextField(verbose_name='نبذة بالعربية')),
                ('about_en', models.TextField(verbose_name='نبذة بالإنجليزية')),
                ('contact_email', models.EmailField(max_length=255, verbose_name='البريد الإلكتروني للتواصل')),
                ('phone_1', models.CharField(max_length=20, verbose_name='الهاتف الأول')),
                ('phone_2', models.CharField(max_length=20, blank=True, null=True, verbose_name='الهاتف الثاني')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('tax_number', models.CharField(max_length=100, blank=True, null=True, verbose_name='الرقم الضريبي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'المؤسسة',
                'verbose_name_plural': 'المؤسسات',
                'ordering': ['-created_at'],
                'db_table': 'api_organization',
                'db_tablespace': '',
            },
        ),
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='api.organization',
                    verbose_name='المؤسسة'
                )),
                ('platform_name', models.CharField(max_length=50, verbose_name='اسم المنصة')),
                ('url', models.URLField(max_length=500, verbose_name='الرابط')),
                ('icon_class', models.CharField(max_length=100, verbose_name='كود الأيقونة')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتيب الظهور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'رابط اجتماعي',
                'verbose_name_plural': 'الروابط الاجتماعية',
                'ordering': ['order_index', 'platform_name'],
                'db_table': 'api_social',
                'db_tablespace': '',
                'indexes': [
                    models.Index(fields=['platform_name'], name='social_platform_name_idx'),
                    models.Index(fields=['is_active'], name='social_is_active_idx'),
                    models.Index(fields=['organization', 'is_active'], name='social_org_active_idx'),
                ],
            },
        ),
        # Add unique constraint to ensure only one organization record (Singleton pattern)
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(
                fields=['id'],
                condition=models.Q(is_active=True),
                name='singleton_active_organization'
            ),
        ),
    ]
