# Generated by Django 6.0.3 on 2026-04-04 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('core', '0003_productmaterial_shipping_maps_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='base_city',
            field=models.ForeignKey(blank=True, help_text='المدينة التي يقع فيها المقر الرئيسي', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='core.shipping', verbose_name='المدينة الأساسية'),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='المستخدم الذي أنشأ السجل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='organization',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='معرف المكان من جوجل لضمان فتح الخريطة بدقة', max_length=255, verbose_name='معرف المكان في جوجل'),
        ),
        migrations.AddField(
            model_name='organization',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='إحداثيات خط العرض من جوجل مابس', max_digits=22, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='organization',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='إحداثيات خط الطول من جوجل مابس', max_digits=22, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='organization',
            name='maps_url',
            field=models.URLField(blank=True, help_text='رابط مباشر لخرائط جوجل', max_length=500, verbose_name='رابط الخريطة'),
        ),
        migrations.AddField(
            model_name='social',
            name='platform_type',
            field=models.CharField(choices=[('public', 'عام (للزبائن)'), ('internal', 'داخلي (للموظفين)'), ('partners', 'شركاء')], default='public', help_text='هل الرابط للزبائن أم للموظفين أم للشركاء', max_length=20, verbose_name='نوع المنصة'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='about_ar',
            field=models.TextField(help_text='قصة المؤسسة ونبذة عنها بالعربية', verbose_name='نبذة بالعربية'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='about_en',
            field=models.TextField(help_text='قصة المؤسسة ونبذة عنها بالإنجليزية', verbose_name='نبذة بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(help_text='عنوان المقر الرئيسي', verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(help_text='البريد الرسمي للتواصل', max_length=255, verbose_name='البريد الإلكتروني للتواصل'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='هل المؤسسة نشطة حالياً', verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(help_text='شعار المؤسسة', max_length=255, upload_to='org/logo/', verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name_ar',
            field=models.CharField(help_text='اسم المؤسسة باللغة العربية', max_length=255, verbose_name='الاسم بالعربية'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name_en',
            field=models.CharField(help_text='اسم المؤسسة باللغة الإنجليزية', max_length=255, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_1',
            field=models.CharField(help_text='رقم الهاتف الرئيسي', max_length=20, verbose_name='الهاتف الأول'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_2',
            field=models.CharField(blank=True, help_text='رقم الهاتف الثانوي', max_length=20, null=True, verbose_name='الهاتف الثاني'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slogan_ar',
            field=models.CharField(help_text='الشعار التسويقي بالعربية', max_length=500, verbose_name='الشعار بالعربية'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slogan_en',
            field=models.CharField(help_text='الشعار التسويقي بالإنجليزية', max_length=500, verbose_name='الشعار بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tax_number',
            field=models.CharField(blank=True, help_text='الرقم الجبائي (NIF/NIS)', max_length=100, null=True, verbose_name='الرقم الضريبي'),
        ),
        migrations.AlterField(
            model_name='social',
            name='icon_class',
            field=models.CharField(help_text='مثل: fa-brands fa-facebook, fa-brands fa-instagram', max_length=100, verbose_name='كود الأيقونة'),
        ),
        migrations.AlterField(
            model_name='social',
            name='is_active',
            field=models.BooleanField(default=True, help_text='هل الرابط نشط ومرئي', verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='social',
            name='order_index',
            field=models.PositiveIntegerField(default=0, help_text='ترتيب ظهور الرابط في القائمة', verbose_name='ترتيب الظهور'),
        ),
        migrations.AlterField(
            model_name='social',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='api.organization', verbose_name='المؤسسة'),
        ),
        migrations.AlterField(
            model_name='social',
            name='platform_name',
            field=models.CharField(help_text='مثل: Facebook, TikTok, Instagram', max_length=50, verbose_name='اسم المنصة'),
        ),
        migrations.AlterField(
            model_name='social',
            name='url',
            field=models.URLField(help_text='رابط الحساب على المنصة', max_length=500, verbose_name='الرابط'),
        ),
        migrations.AlterUniqueTogether(
            name='social',
            unique_together={('organization', 'platform_name')},
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='org_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['base_city'], name='org_base_city_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_by'], name='org_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='social',
            index=models.Index(fields=['platform_type'], name='social_platform_type_idx'),
        ),
        migrations.AddIndex(
            model_name='social',
            index=models.Index(fields=['order_index'], name='social_order_idx'),
        ),
    ]
