# Generated by Django 6.0.3 on 2026-04-07 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_order_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coupon',
            new_name='api_coupon_code_f609b1_idx',
            old_name='api_coupon_code_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='api_coupon_is_acti_e05ca5_idx',
            old_name='api_coupon_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='api_coupon_valid_f_44111e_idx',
            old_name='api_coupon_valid_from_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='api_coupon_valid_t_232b2c_idx',
            old_name='api_coupon_valid_to_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='api_order_order_n_ec9cdb_idx',
            old_name='api_order_order_number_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='api_order_user_id_764746_idx',
            old_name='api_order_user_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='api_order_status_dee4b6_idx',
            old_name='api_order_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='api_order_created_7fb22c_idx',
            old_name='api_order_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='api_order_wilaya__80e1ab_idx',
            old_name='api_order_wilaya_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='api_order_payment_80590b_idx',
            old_name='api_order_payment_method_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='api_orderit_order_i_3f9c70_idx',
            old_name='api_orderitem_order_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='api_orderit_product_1a13b6_idx',
            old_name='api_orderitem_product_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='api_orderit_materia_e111c6_idx',
            old_name='api_orderitem_material_idx',
        ),
        migrations.RenameIndex(
            model_name='ordertimeline',
            new_name='api_orderti_order_i_415b67_idx',
            old_name='api_ordertimeline_order_idx',
        ),
        migrations.RenameIndex(
            model_name='ordertimeline',
            new_name='api_orderti_status_923eb7_idx',
            old_name='api_ordertimeline_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ordertimeline',
            new_name='api_orderti_timesta_dfe5a0_idx',
            old_name='api_ordertimeline_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='api_payment_order_i_376f77_idx',
            old_name='api_payment_order_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='api_payment_status_c61efc_idx',
            old_name='api_payment_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='api_payment_transac_0db71d_idx',
            old_name='api_payment_transaction_id_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='api_payment_created_c18666_idx',
            old_name='api_payment_created_at_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordertimeline',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
