# Generated by Django 6.0.3 on 2026-04-07 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_orderitem_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(default='VinylArt', help_text='اسم المؤسسة باللغة العربية', max_length=255, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(default='VinylArt', help_text='اسم المؤسسة باللغة الإنجليزية', max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('logo', models.ImageField(help_text='شعار المؤسسة', max_length=255, upload_to='org/logo/', verbose_name='الشعار')),
                ('slogan_ar', models.CharField(help_text='الشعار التسويقي بالعربية', max_length=500, verbose_name='الشعار بالعربية')),
                ('slogan_en', models.CharField(help_text='الشعار التسويقي بالإنجليزية', max_length=500, verbose_name='الشعار بالإنجليزية')),
                ('about_ar', models.TextField(help_text='قصة المؤسسة ونبذة عنها بالعربية', verbose_name='نبذة بالعربية')),
                ('about_en', models.TextField(help_text='قصة المؤسسة ونبذة عنها بالإنجليزية', verbose_name='نبذة بالإنجليزية')),
                ('contact_email', models.EmailField(help_text='البريد الرسمي للتواصل', max_length=255, verbose_name='البريد الإلكتروني للتواصل')),
                ('phone_1', models.CharField(help_text='رقم الهاتف الرئيسي', max_length=20, verbose_name='الهاتف الأول')),
                ('phone_2', models.CharField(blank=True, help_text='رقم الهاتف الثانوي', max_length=20, null=True, verbose_name='الهاتف الثاني')),
                ('address', models.TextField(help_text='عنوان المقر الرئيسي', verbose_name='العنوان')),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, help_text='إحداثيات خط العرض من جوجل مابس', max_digits=22, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, help_text='إحداثيات خط الطول من جوجل مابس', max_digits=22, null=True, verbose_name='خط الطول')),
                ('google_place_id', models.CharField(blank=True, help_text='معرف المكان من جوجل لضمان فتح الخريطة بدقة', max_length=255, verbose_name='معرف المكان في جوجل')),
                ('maps_url', models.URLField(blank=True, help_text='رابط مباشر لخرائط جوجل', max_length=500, verbose_name='رابط الخريطة')),
                ('tax_number', models.CharField(blank=True, help_text='الرقم الجبائي (NIF/NIS)', max_length=100, null=True, verbose_name='الرقم الضريبي')),
                ('is_active', models.BooleanField(default=True, help_text='هل المؤسسة نشطة حالياً', verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('base_city', models.ForeignKey(blank=True, help_text='المدينة التي يقع فيها المقر الرئيسي', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='api.shipping', verbose_name='المدينة الأساسية')),
                ('created_by', models.ForeignKey(blank=True, help_text='المستخدم الذي أنشأ السجل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'المؤسسة',
                'verbose_name_plural': 'المؤسسات',
                'db_table': 'api_organization',
                'ordering': ['-created_at'],
                'db_tablespace': '',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(help_text='مثل: Facebook, TikTok, Instagram', max_length=50, verbose_name='اسم المنصة')),
                ('platform_type', models.CharField(choices=[('public', 'عام (للزبائن)'), ('internal', 'داخلي (للموظفين)'), ('partners', 'شركاء')], default='public', help_text='هل الرابط للزبائن أم للموظفين أم للشركاء', max_length=20, verbose_name='نوع المنصة')),
                ('url', models.URLField(help_text='رابط الحساب على المنصة', max_length=500, verbose_name='الرابط')),
                ('icon_class', models.CharField(help_text='مثل: fa-brands fa-facebook, fa-brands fa-instagram', max_length=100, verbose_name='كود الأيقونة')),
                ('order_index', models.PositiveIntegerField(default=0, help_text='ترتيب ظهور الرابط في القائمة', verbose_name='ترتيب الظهور')),
                ('is_active', models.BooleanField(default=True, help_text='هل الرابط نشط ومرئي', verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='api.organization', verbose_name='المؤسسة')),
            ],
            options={
                'verbose_name': 'رابط اجتماعي',
                'verbose_name_plural': 'الروابط الاجتماعية',
                'db_table': 'api_social',
                'ordering': ['order_index', 'platform_name'],
                'db_tablespace': '',
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='org_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['base_city'], name='org_base_city_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_by'], name='org_created_by_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('id',), name='singleton_active_organization'),
        ),
        migrations.AddIndex(
            model_name='social',
            index=models.Index(fields=['platform_name'], name='social_platform_name_idx'),
        ),
        migrations.AddIndex(
            model_name='social',
            index=models.Index(fields=['is_active'], name='social_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='social',
            index=models.Index(fields=['organization', 'is_active'], name='social_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='social',
            index=models.Index(fields=['platform_type'], name='social_platform_type_idx'),
        ),
        migrations.AddIndex(
            model_name='social',
            index=models.Index(fields=['order_index'], name='social_order_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='social',
            unique_together={('organization', 'platform_name')},
        ),
    ]
