# Generated by Django 6.0.3 on 2026-04-04 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate_sample_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='shipping',
            name='maps_url',
            field=models.URLField(blank=True, help_text='رابط مباشر لخرائط جوجل لنقطة الاستلام', max_length=500, verbose_name='رابط الخريطة'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='إحداثيات خط العرض لنقطة الاستلام أو مركز التوزيع', max_digits=22, null=True, verbose_name='خط عرض نقطة الاستلام'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='إحداثيات خط الطول لنقطة الاستلام أو مركز التوزيع', max_digits=22, null=True, verbose_name='خط طول نقطة الاستلام'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='radius_km',
            field=models.IntegerField(blank=True, help_text='نطاق التوصيل بالكيلومتر حول المقر الرئيسي', null=True, verbose_name='نطاق التوصيل بالكيلومتر'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product'], name='core_produc_product_b0d6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_main'], name='core_produc_product_e8080b_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'sort_order'], name='core_produc_product_ad304f_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['is_main'], name='core_produc_is_main_a23ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['sort_order'], name='core_produc_sort_or_305757_idx'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='core.material'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_materials', to='core.product'),
        ),
        migrations.AddIndex(
            model_name='productmaterial',
            index=models.Index(fields=['product'], name='core_produc_product_f86270_idx'),
        ),
        migrations.AddIndex(
            model_name='productmaterial',
            index=models.Index(fields=['material'], name='core_produc_materia_d39909_idx'),
        ),
        migrations.AddIndex(
            model_name='productmaterial',
            index=models.Index(fields=['product', 'is_active'], name='core_produc_product_dac6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='productmaterial',
            index=models.Index(fields=['material', 'is_active'], name='core_produc_materia_bf126b_idx'),
        ),
        migrations.AddIndex(
            model_name='productmaterial',
            index=models.Index(fields=['product', 'material'], name='core_produc_product_6d99a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productmaterial',
            unique_together={('product', 'material')},
        ),
    ]
